// Petal Panic — Theater Effect Metadata (debug-only).
// Hardcoded descriptions + param lists for the theater info panel.
// NOT loaded in gameplay.

export const EFFECT_META = {
  'particle-burst': {
    desc: 'Spawns small particles from a point. Used for impacts, hits, pickups.',
    params: [
      { key: 'count',       config: true,  desc: 'Number of particles' },
      { key: 'size',        config: false, desc: 'Particle size (px)' },
      { key: 'speed',       config: false, desc: 'Ejection speed (px/s)' },
      { key: 'direction',   config: false, desc: 'Spread angle / arc' },
      { key: 'lifetime',    config: false, desc: 'Survival time (s)' },
      { key: 'gravity',     config: false, desc: 'Downward pull' },
      { key: 'color',       config: false, desc: 'Tint color' },
      { key: 'spawnRadius', config: false, desc: 'Origin scatter area' },
    ],
  },
  explosion: {
    desc: 'Localized burst effect. Visual only — no damage.',
    params: [
      { key: 'radius',       config: true,  desc: 'Blast size (px)' },
      { key: 'count',        config: true,  desc: 'Particle count override' },
      { key: 'duration',     config: false, desc: 'Total lifetime (s)' },
      { key: 'intensity',    config: false, desc: 'Brightness / scale' },
      { key: 'style',        config: false, desc: 'Visual variant' },
      { key: 'growthRate',   config: false, desc: 'Expansion speed' },
    ],
  },
  debris: {
    desc: 'Directional fragments from an impact or destroyed object.',
    params: [
      { key: 'fragmentCount', config: true,  desc: 'Number of pieces' },
      { key: 'velocity',      config: true,  desc: 'Initial speed (px/s)' },
      { key: 'direction',     config: true,  desc: 'Launch angle (rad)' },
      { key: 'spread',        config: true,  desc: 'Arc width (rad)' },
      { key: 'gravity',       config: true,  desc: 'Downward pull' },
      { key: 'rotation',      config: true,  desc: 'Spin speed' },
      { key: 'lifetime',      config: true,  desc: 'Survival time (s)' },
      { key: 'size',          config: true,  desc: 'Fragment size (px)' },
    ],
  },
  'ground-wave': {
    desc: 'Horizontal wave traveling along the ground plane.',
    params: [
      { key: 'direction', config: true, desc: 'Travel direction' },
      { key: 'speed',     config: true, desc: 'Wave speed (px/s)' },
      { key: 'distance',  config: true, desc: 'Travel distance (px)' },
      { key: 'height',    config: true, desc: 'Wave crest height' },
      { key: 'width',     config: true, desc: 'Wave front width' },
      { key: 'duration',  config: true, desc: 'Total lifetime (s)' },
      { key: 'style',     config: true, desc: 'Visual variant' },
    ],
  },
  shockwave: {
    desc: 'Expanding circular ring from a point origin.',
    params: [
      { key: 'startRadius',    config: true, desc: 'Initial radius (px)' },
      { key: 'maxRadius',      config: true, desc: 'Final radius (px)' },
      { key: 'expansionSpeed', config: true, desc: 'Growth rate (px/s)' },
      { key: 'thickness',      config: true, desc: 'Ring width (px)' },
      { key: 'opacity',        config: true, desc: 'Peak alpha (0-1)' },
      { key: 'duration',       config: true, desc: 'Total lifetime (s)' },
      { key: 'color',          config: true, desc: 'Ring tint' },
    ],
  },
  trail: {
    desc: 'Ribbon following a moving carrier. Speed comes from the entity.',
    params: [
      { key: 'length',   config: true, desc: 'Max ribbon length (px)' },
      { key: 'width',    config: true, desc: 'Head thickness (px)' },
      { key: 'lifetime', config: true, desc: 'Point survival (s)' },
      { key: 'opacity',  config: true, desc: 'Peak alpha (0-1)' },
      { key: 'density',  config: true, desc: 'Min spacing (px)' },
      { key: 'offset',   config: true, desc: 'Perpendicular shift' },
    ],
  },
  afterimage: {
    desc: 'Translucent ghost copies behind a fast-moving sprite.',
    params: [
      { key: 'count',         config: true, desc: 'Max ghost frames' },
      { key: 'spawnInterval', config: true, desc: 'Frames between ghosts' },
      { key: 'lifetime',      config: true, desc: 'Ghost survival (s)' },
      { key: 'opacity',       config: true, desc: 'Peak alpha (0-1)' },
      { key: 'fadeRate',      config: true, desc: 'Fade speed' },
      { key: 'offset',        config: true, desc: 'Position offset' },
      { key: 'color',         config: true, desc: 'Tint color' },
    ],
  },
  'telegraph-circle': {
    desc: 'Warning circle before an attack. Shrinks toward center.',
    params: [
      { key: 'radius',       config: true, desc: 'Starting radius (px)' },
      { key: 'minRadius',    config: true, desc: 'Shrink target (px)' },
      { key: 'shrinkRate',   config: true, desc: 'Contraction speed' },
      { key: 'pulseRate',    config: true, desc: 'Pulse frequency (Hz)' },
      { key: 'thickness',    config: true, desc: 'Ring width (px)' },
      { key: 'opacity',      config: true, desc: 'Peak alpha (0-1)' },
      { key: 'duration',     config: true, desc: 'Total lifetime (s)' },
      { key: 'followTarget', config: true, desc: 'Track moving carrier' },
      { key: 'color',        config: true, desc: 'Ring tint' },
    ],
  },
  'ground-target-marker': {
    desc: 'Fixed target marker on the ground. Player can escape.',
    params: [
      { key: 'radius',    config: true, desc: 'Marker radius (px)' },
      { key: 'pulseRate', config: true, desc: 'Pulse frequency (Hz)' },
      { key: 'rotation',  config: true, desc: 'Spin speed (rad/s)' },
      { key: 'opacity',   config: true, desc: 'Peak alpha (0-1)' },
      { key: 'duration',  config: true, desc: 'Total lifetime (s)' },
      { key: 'animation', config: true, desc: 'Animation variant' },
      { key: 'color',     config: true, desc: 'Marker tint' },
    ],
  },
  'target-reticle': {
    desc: 'Tracking reticle that follows a moving target entity.',
    params: [
      { key: 'size',          config: true, desc: 'Reticle size (px)' },
      { key: 'rotationSpeed', config: true, desc: 'Spin speed (rad/s)' },
      { key: 'pulseRate',     config: true, desc: 'Pulse frequency (Hz)' },
      { key: 'offset',        config: true, desc: 'Position offset' },
      { key: 'opacity',       config: true, desc: 'Peak alpha (0-1)' },
      { key: 'duration',      config: true, desc: 'Total lifetime (s)' },
      { key: 'followMode',    config: true, desc: 'Track carrier live' },
      { key: 'color',         config: true, desc: 'Reticle tint' },
    ],
  },
  vignette: {
    desc: 'Edge darkening overlay when hero takes damage.',
    params: [
      { key: 'strength', config: true,  desc: 'Intensity (0-1)' },
      { key: 'color',    config: false, desc: 'Tint color' },
      { key: 'duration', config: false, desc: 'Fade-out time (s)' },
      { key: 'fadeIn',   config: false, desc: 'Ramp-up time (s)' },
      { key: 'fadeOut',  config: false, desc: 'Ramp-down time (s)' },
    ],
  },
  'sprite-flash': {
    desc: 'Flashes or tints a sprite. Damage feedback, invincibility.',
    params: [
      { key: 'color',          config: true, desc: 'Flash tint' },
      { key: 'duration',       config: true, desc: 'Total lifetime (s)' },
      { key: 'flashFrequency', config: true, desc: 'Blink rate (Hz)' },
      { key: 'flashes',        config: true, desc: 'Number of blinks' },
      { key: 'opacity',        config: true, desc: 'Peak alpha (0-1)' },
      { key: 'blendIntensity', config: true, desc: 'Blend strength' },
    ],
  },
  'camera-shake': {
    desc: 'Shakes the game camera. All world objects move together.',
    params: [
      { key: 'intensity',   config: true, desc: 'Shake magnitude (px)' },
      { key: 'duration',    config: true, desc: 'Total lifetime (s)' },
      { key: 'frequency',   config: true, desc: 'Oscillation rate (Hz)' },
      { key: 'hStrength',   config: true, desc: 'Horizontal multiplier' },
      { key: 'vStrength',   config: true, desc: 'Vertical multiplier' },
      { key: 'decay',       config: true, desc: 'Damping exponent' },
    ],
  },
  'screen-flash': {
    desc: 'Brief full-viewport color overlay. Explosions, lightning.',
    params: [
      { key: 'strength', config: true,  desc: 'Peak opacity (0-1)' },
      { key: 'color',    config: false, desc: 'Flash color' },
      { key: 'duration', config: false, desc: 'Fade-out time (s)' },
      { key: 'fadeIn',   config: false, desc: 'Ramp-up time (s)' },
      { key: 'fadeOut',  config: false, desc: 'Ramp-down time (s)' },
    ],
  },
  'sprite-shake': {
    desc: 'Localized jitter on a single sprite. No camera movement.',
    params: [
      { key: 'amount',   config: true,  desc: 'Max offset per axis (px)' },
      { key: 'frequency',config: false, desc: 'Jitter rate (Hz)' },
      { key: 'duration', config: false, desc: 'Total lifetime (s)' },
      { key: 'decay',    config: false, desc: 'Damping over time' },
    ],
  },
  'impact-star': {
    desc: 'Short visual pop at exact impact point. Punches, bullets.',
    params: [
      { key: 'size',       config: true, desc: 'Star size (px)' },
      { key: 'duration',   config: true, desc: 'Pop lifetime (s)' },
      { key: 'rotation',   config: true, desc: 'Initial angle (rad)' },
      { key: 'opacity',    config: true, desc: 'Peak alpha (0-1)' },
      { key: 'style',      config: true, desc: 'star or burst' },
      { key: 'scaleCurve', config: true, desc: 'Growth easing' },
    ],
  },
  'fade-out': {
    desc: 'Gradually reduces opacity until the sprite disappears.',
    params: [
      { key: 'startOpacity', config: true, desc: 'Initial alpha (0-1)' },
      { key: 'endOpacity',   config: true, desc: 'Final alpha (0-1)' },
      { key: 'duration',     config: true, desc: 'Fade time (s)' },
      { key: 'delay',        config: true, desc: 'Wait before fade (s)' },
      { key: 'curve',        config: true, desc: 'Easing function' },
    ],
  },
  'scale-pulse': {
    desc: 'Temporarily grows/shrinks a visual element. Charging, pickups.',
    params: [
      { key: 'startScale',     config: true, desc: 'Initial scale' },
      { key: 'maxScale',       config: true, desc: 'Upper bound' },
      { key: 'minScale',       config: true, desc: 'Lower bound' },
      { key: 'pulseFrequency', config: true, desc: 'Cycles per second' },
      { key: 'loopCount',      config: true, desc: 'Number of cycles' },
      { key: 'delay',          config: true, desc: 'Wait before start (s)' },
    ],
  },
  'squash-stretch': {
    desc: 'Distorts scale along X/Y axes. Landings, jumps, impacts.',
    params: [
      { key: 'xScale',           config: true, desc: 'X-axis target scale' },
      { key: 'yScale',           config: true, desc: 'Y-axis target scale' },
      { key: 'duration',         config: true, desc: 'Squash time (s)' },
      { key: 'recoveryDuration', config: true, desc: 'Return-to-normal (s)' },
      { key: 'intensity',        config: true, desc: 'Effect strength' },
      { key: 'delay',            config: true, desc: 'Wait before start (s)' },
    ],
  },
  'dust-cloud': {
    desc: 'Ground particles around a contact point. Landings, stomps.',
    params: [
      { key: 'particleCount', config: true, desc: 'Number of puffs' },
      { key: 'spread',        config: true, desc: 'Scatter radius (px)' },
      { key: 'size',          config: true, desc: 'Puff size (px)' },
      { key: 'velocity',      config: true, desc: 'Ejection speed (px/s)' },
      { key: 'lifetime',      config: true, desc: 'Survival time (s)' },
      { key: 'opacity',       config: true, desc: 'Peak alpha (0-1)' },
      { key: 'gravity',       config: true, desc: 'Downward pull' },
    ],
  },
  'attack-arc': {
    desc: 'Fast visual arc for melee attacks. Claws, blades, sweeps.',
    params: [
      { key: 'arcAngle',     config: true, desc: 'Sweep angle (rad)' },
      { key: 'radius',       config: true, desc: 'Arc radius (px)' },
      { key: 'thickness',    config: true, desc: 'Stroke width (px)' },
      { key: 'duration',     config: true, desc: 'Sweep lifetime (s)' },
      { key: 'orientation',  config: true, desc: 'Base angle (rad)' },
      { key: 'opacity',      config: true, desc: 'Peak alpha (0-1)' },
      { key: 'followEntity', config: true, desc: 'Track carrier' },
      { key: 'sweepDirection', config: true, desc: 'CW or CCW' },
      { key: 'color',        config: true, desc: 'Arc tint' },
    ],
  },
  'aura-glow': {
    desc: 'Glow or aura around/behind a sprite. Power-ups, boss states.',
    params: [
      { key: 'radius',    config: true, desc: 'Glow extent (px)' },
      { key: 'opacity',   config: true, desc: 'Peak alpha (0-1)' },
      { key: 'pulseRate', config: true, desc: 'Pulse frequency (Hz)' },
      { key: 'intensity', config: true, desc: 'Glow strength' },
      { key: 'color',     config: true, desc: 'Aura tint' },
      { key: 'duration',  config: true, desc: 'Total lifetime (s)' },
      { key: 'offset',    config: true, desc: 'Center offset {x,y}' },
    ],
  },
  'screen-overlay': {
    desc: 'Persistent viewport layer. Boss phases, danger states, mood.',
    params: [
      { key: 'color',     config: true, desc: 'Overlay tint' },
      { key: 'opacity',   config: true, desc: 'Peak alpha (0-1)' },
      { key: 'duration',  config: true, desc: 'Total lifetime (s)' },
      { key: 'fadeIn',    config: true, desc: 'Ramp-up time (s)' },
      { key: 'fadeOut',   config: true, desc: 'Ramp-down time (s)' },
      { key: 'blendMode', config: true, desc: 'Canvas composite op' },
    ],
  },
  'composite-explosion': {
    desc: 'Multiple explosions at random positions over time. Boss deaths.',
    params: [
      { key: 'radius',         config: true, desc: 'Area radius (px)' },
      { key: 'explosionCount', config: true, desc: 'Total sub-explosions' },
      { key: 'spawnInterval',  config: true, desc: 'Time between spawns' },
      { key: 'timingVariance', config: true, desc: 'Random timing spread' },
      { key: 'posVariance',    config: true, desc: 'Random position spread' },
      { key: 'childType',      config: true, desc: 'Child effect type' },
      { key: 'childSizeRange', config: true, desc: '[min, max] sizes' },
      { key: 'duration',       config: true, desc: 'Total lifetime (s)' },
      { key: 'density',        config: true, desc: 'Overlap factor' },
    ],
  },
  beam: {
    desc: 'Directional rectangular beam. Lightsaber-style directional strike.',
    params: [
      { key: 'length',         config: true,  desc: 'Beam length (px)' },
      { key: 'width',          config: true,  desc: 'Beam width (px)' },
      { key: 'gradientRadius', config: true,  desc: 'Halo extent (px)' },
      { key: 'color',          config: true,  desc: 'Energy tint' },
      { key: 'flashInTime',    config: true,  desc: 'Ignition time (s)' },
      { key: 'fadeOutTime',    config: true,  desc: 'Fade-out time (s)' },
      { key: 'holdTime',       config: false, desc: 'Sustain time (s) — v2' },
      { key: 'orientation',    config: true,  desc: 'Beam angle (rad)' },
      { key: 'opacity',        config: true,  desc: 'Peak alpha (0-1)' },
      { key: 'coreAlpha',      config: true,  desc: 'Core brightness' },
    ],
  },
};
